Paths:
  MTV_PROG_PATH: "/home/pimedia/MTV2"

Media:
  MTV_MOVIES_PATH: "/home/pimedia/PINAS/MTV/Movies/"
  MTV_TV_PATH: "/home/pimedia/PINAS/MTV/TVShows/"

Posters:
  MTV_POSTER_PATH: "/home/pimedia/PINAS/MTV/Posters/"
  MTV_TVPOSTER_PATH: "/home/pimedia/PINAS/MTV/TVPosters/"

Thumbnails:
  MTV_THUMBNAIL_PATH: "/usr/share/MTV2/thumbnails/"
  MTV_TVTHUMBNAIL_PATH: "/usr/share/MTV2/tvthumbnails/"
  # Alternate paths (commented out)
  # MTV_THUMBNAIL_PATH: "/home/pimedia/MTV2/MTVP2/thumbnails/"
  # MTV_TVTHUMBNAIL_PATH: "/home/pimedia/MTV2/MTVP2/tvthumbnails/"

DBs:
  MTV_DB_PATH: "/usr/share/MTV2/mtv.db"
  PROPANE_DB_PATH: "/usr/share/MTV2/propane.db"

Server:
  MTV_SERVER_ADDR: "http://10.0.4.41"
  MTV_RAW_ADDR: "10.0.4.41"
  MTV_SERVER_PORT: 7777
  # Alternate port (commented out)
  # MTV_SERVER_PORT: 80

Misc:
  MTV_PID_FILE: "/usr/share/MTV2/mtvpid.txt"
  MTV_OFFSET: 25